package com.inventory.utility;

import com.inventory.model.Product;
import java.io.*;
import java.util.*;
import java.text.SimpleDateFormat;

public class CSVHelper {

    private static final String REPORT_DIR = "reports/";

    public static String writeProductsCSV(List<Product> products, String generatedBy) {

        try {
            File dir = new File(REPORT_DIR);
            if (!dir.exists()) {
                dir.mkdirs();
            }

            String filename = REPORT_DIR + "Products_inventory_report_" +
                    new SimpleDateFormat("yyyyMMdd_HHmmss").format(new Date()) + ".csv";

            try (PrintWriter writer = new PrintWriter(new FileWriter(filename))) {

                writer.println("========== 📦 PRODUCTS INVENTORY REPORT 📦 ==========");
                writer.println("Report Generated By: " + generatedBy);
                writer.println("Report Generated On: " +
                        new SimpleDateFormat("dd-MM-yyyy HH:mm:ss").format(new Date()));
                writer.println("===================================================");
                writer.println("ID,NAME,CATEGORY,QUANTITY,PRICE");

                if (products != null && !products.isEmpty()) {
                    for (Product p : products) {
                        writer.println(p.getId() + "," + p.getName() + "," + p.getCategory() + "," +
                                p.getQuantity() + "," + p.getPrice());
                    }
                } else {
                    writer.println("⚠️ No Products Available");
                }

                writer.println("===================================================");
                writer.println("Total Products Available: " + (products != null ? products.size() : 0));
            }

            System.out.println("Report saved successfully at: " + filename);
            return filename;

        } catch (IOException e) {
            System.out.println("Error generating report: " + e.getMessage());
            return null;
        }
    }
}
